# Generated by Django 3.0 on 2019-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cmc', models.IntegerField()),
                ('colors', models.CharField(max_length=45)),
                ('set', models.CharField(max_length=45)),
                ('rarity', models.CharField(max_length=45)),
            ],
        ),
    ]
