# Generated by Django 3.0 on 2019-12-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('Creature', 'Creature'), ('Artifact', 'Artifact'), ('Enchantment', 'Enchantment'), ('Instant', 'Instant'), ('Sorcery', 'Sorcery'), ('Land', 'Land')], default='defaultval', max_length=45),
            preserve_default=False,
        ),
    ]
