# Generated by Django 3.0 on 2019-12-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('M', 'Mystic Rare')], max_length=45),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('C', 'Creature'), ('A', 'Artifact'), ('E', 'Enchantment'), ('I', 'Instant'), ('S', 'Sorcery'), ('L', 'Land')], max_length=45),
        ),
    ]
