# Generated by Django 3.0 on 2019-12-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20191213_0625'),
    ]

    operations = [
    ]
