# Generated by Django 3.0 on 2019-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20191213_0627'),
    ]

    operations = [
    ]
