# Generated by Django 3.0 on 2019-12-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20191213_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green'), ('C', 'Colorless'), ('M', 'Multicolored')], max_length=45),
        ),
    ]
