# Generated by Django 3.0 on 2019-12-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20191213_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Mythic Rare', 'Mythic Rare')], max_length=45),
        ),
    ]
