# Generated by Django 3.0 on 2019-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dci_num', models.IntegerField()),
                ('fname', models.CharField(max_length=45)),
                ('mi', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=45)),
            ],
        ),
    ]
