# Generated by Django 3.0 on 2019-12-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191212_2154'),
        ('match', '0002_match_player_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to='players.Player'),
        ),
    ]
