# Generated by Django 3.0 on 2019-12-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_game_store'),
        ('players', '0002_auto_20191212_2154'),
        ('match', '0004_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='players.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_one_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_two_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
