# Generated by Django 3.0 on 2019-12-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191213_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='game_store',
        ),
    ]
