# Generated by Django 3.0 on 2019-12-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_deck_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='card',
            new_name='cards',
        ),
    ]
