# Generated by Django 3.0 on 2019-12-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_auto_20191212_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='deck_name',
            new_name='name',
        ),
    ]
