# Generated by Django 3.0 on 2019-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0007_auto_20191213_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='format',
            field=models.CharField(default='Modern', max_length=45),
            preserve_default=False,
        ),
    ]
