# Generated by Django 3.0 on 2019-12-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20191213_1205'),
        ('deck', '0008_deck_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.Card'),
        ),
    ]
