# Generated by Django 3.0 on 2019-12-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestore',
            name='address',
        ),
        migrations.AddField(
            model_name='gamestore',
            name='city',
            field=models.CharField(default='defaultval', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestore',
            name='state',
            field=models.CharField(default='defaultval', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestore',
            name='street',
            field=models.CharField(default='defaultval', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestore',
            name='zip',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
